### ISSUE TITLE
Maps:  same Channel + Event ID, but different Providers

### ISSUE THREAD

**Issue by karch4n6** [EricZimmerman/evtx#47]
Is there any way to accommodate separate maps where Channel and EventID are the same across both, but Provider is different?  I have a very rough workaround using separate \maps directories or renaming System_1.map in between runs, but would love to map both instances in one shot if possible.

Example:

EventId: 1
Channel: "System"
Provider: "Microsoft-Windows-Power-Troubleshooter"

EventId: 1
Channel: "System"
Provider: "Microsoft-Windows-Kernel-General"

Thanks!

**Comment by rathbuna** [comment]
You see this a lot in the Application log, too. Lots of Event ID 1's out there. Really, the lower the number the more likely there's other Providers that use those same Event IDs. 

One idea is to change the naming convention for maps to Channel_Provider_EventID.map. That way, it's more on people's radars that the Provider is important. One of my to-do items is to make sure every map has a Provider listed even if there's no other overlapping Event IDs by other Providers. That would be for consistency and future proofing maps in the case that eventually another Channel/Provider decides to use, for example, 7045 as an Event ID. 

Up until recently, we had the map for potentially exploiting a known vulnerability mapping for every Event ID (forget the number exactly, it's early) regardless of Provider due to lack of a Provider being specified. Lots of false positives in the Map Description column, as a result. 

Am I understanding correctly that your idea effectively would be to change the naming convention to EventID.map so ALL numbered events are self contained within one single map, regardless of Provider/Channel?

**Comment by EricZimmerman** [comment]
the program does not care of you name all the maps a different way, as long as they end with the proper extension, so rename away.

what you cannot do is just slam all the yaml into a single file, so 7045.map wont be a thing

that wont work. thats not granular either and the other downside is someone making a mistake in one place in a monolithic file risks breaking all the other maps or i have to then add logic to cut up the large file, etc.

what if someone does not want all the other maps? now they have to edit out larger maps all over the place, vs locating them based on filename in the maps directory.

if we need to expand the default names, i like this:

Channel_Provider_EventID.map


if need be i can make provider mandatory. this would help with the dictionary too, so i can quickly look up the proper map, but as is, its just channel and event id, like this:

var map = EventLog.EventLogMaps[$"{EventId}-{Channel.ToUpperInvariant()}"];

if i make provider required, we can do this:

var map = EventLog.EventLogMaps[$"{EventId}-{Provider}-{Channel.ToUpperInvariant()}"];

and so on. its not a big deal to make that change, but ALL the maps would need to be updated, adding in the Provider property (and it must match)

so back  to the OPs question, cant 2 maps just be used, adding in the provider to the filename? problem solved

**Comment by rathbuna** [comment]
@EricZimmerman I will make a run through all the maps and populate all the maps I can with a Provider. I already did all the Sysmon maps this morning. Give me a couple days depending on if some of the more obscure ones I can't reproduce on my own system I have to do some hunting for.

**Comment by rathbuna** [comment]
I just did a preliminary search and only 40 of the 195 current maps have a hit for "Provider: " so I will get started and see how far I can get before I have to do some digging.

**Comment by EricZimmerman** [comment]
i think that makes the most sense. adding the provider to all maps first, then me making it mandatory, ensures nothing breaks. i can then tweak the internals to look for the provider as well. 

from there we can rename maps (or you will do this in step 1 i guess) and we have met the goals

**Comment by rathbuna** [comment]
Yep, sounds good to me. I will be renaming as I go along. I am thinking Channel-Name_Provider-Name_EventID.map. 

For instance, the current name for Application-Sophos-Alert_42.map would change to Application_Sophos-Alert_42.map with the _ separating Channel from Provider from EventID and - would account for any spaces/special characters in the Provider for the purpose of the filename. 

Another example, System_7045.map to System_Service-Control-Manager_7045.map, and so on. 

Thoughts on that before I move on the renaming process? I'm already well into adding Providers to many of the maps that are missing one.

**Comment by EricZimmerman** [comment]
works for me. update the readme.md as well, so others can see the pattern, along with those examples for reference.

the map names get longer, but that wont matter much at all, and its much clearer now

**Comment by karch4n6** [comment]
Ah - did not realize I could just rename... Expanding the names as you've described above would be very helpful. Thanks again!

**Comment by rathbuna** [comment]
> Ah - did not realize I could just rename... Expanding the names as you've described above would be very helpful. Thanks again!

Already in progress. Thanks for bringing it up and sparking the discussion.

**Comment by rathbuna** [comment]
Provider field has been populated for all maps. Next up, renaming each map.

**Comment by rathbuna** [comment]
@EricZimmerman this is now done. All maps have been renamed.
